# switch this to false you want to start in DEVMODE
# https://www.vaultproject.io/intro/getting-started/dev-server.html
[dev]
mode = true

[backend]
storage = "file"
path = "vault"

[listener]
type = "tcp"
location = "127.0.0.1"
port = 8200
tls_disable = true
cert_file = "/etc/ssl/certs/snakeoil.pem"
key_file = "/etc/ssl/private/snakeoil.key"
